POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imtha2UiLCJpZCI6IjVlZDQxNDQ2Y2MzOTI2MzQwODQzZjI4NyIsImlhdCI6MTYwMTEzOTk2NH0.o85XUKy5hc9I_lolihy8rSeG_s4UWwFryemMuLza4_s

{
  "title": "First class is even cheaper", 
  "author": "Kake Kekäläinen", 
  "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.html", 
  "likes": 200, 
  "userId": "5ecd70f09e9d0035fcd606ed",
  "comment": "No jopas jotakin!"
}